### PR TITLE
Implementation of i18n localization added.

### PR DESCRIPTION
**Pull request by utkusaridede**
ToDo:

- All languages will be added to localization.
- Some typos will be fixed.
- Non translated text will be replaced.
- Refactoring on gatsby react-i18n theme will be done.
- Automatically adding readily translated posts (news) to graphQL will be implemented.

Done:

- Localization added to header and README updated.
- Localization added to pages and plain text replaced.
- Basic language switcher added to the footer and plain text replaced.
- Old locale files, config, and utils added. EN and TR are ready to check functionality.
- Localization (react-i18n) dependencies and config added.

### CODE REVIEW

**Comment by ressonix** [comment]
This looks like awesome progress so far! Looks like the deployment to Vercel for preview didn't quite make it through, so you'll need to use the inspect link and make sure those issues are resolved, but it's looking good so far!

**Comment by utkusaridede** [comment]
Thank you! If I click the vercel preview, it redirects me to the 404 page. Do you have any idea what is wrong with my account?

**Comment by arevaldez** [comment]
Can confirm, mine says 404 as well. Not sure why?

**Comment by hbjydev** [comment]
It's probably because @ressonix hasn't got his Vercel configured properly. I'll discuss to fix this with him on Mattermost. :)

**Comment by ressonix** [comment]
Should be fixed now :))

**Comment by hbjydev** [comment]
Yep! @arevaldez @utkusaridede Y'all should be able to check it now :)

**Comment by hbjydev** [comment]
```
20:27:53.199 | error Building static HTML failed for path "/news/community-update-december-2020/"
-- | --
20:27:53.208 | 6 \| import { Translate } from '../../i18n/utils/translate';
20:27:53.208 | 7 \|
20:27:53.208 | >  8 \| const Header = ({ pageContext: { locale: language } }) => {
20:27:53.208 | \|                                          ^
20:27:53.208 | 9 \|
20:27:53.208 | 10 \|   const [isOpen, setIsOpen] = useState(false);
20:27:53.208 | 11 \|   const translate = Translate();
20:27:53.208 |  
20:27:53.208 | WebpackError: TypeError: Cannot read property 'locale' of undefined
20:27:53.208 |  
20:27:53.208 | - index.jsx:8
20:27:53.209 | src/components/header/index.jsx:8:42
```

Looks like content pages are trying to use locale stuffs?

**Comment by arevaldez** [comment]
It's working. Thanks Y'all 👍 @hbjydev @ressonix

**Comment by utkusaridede** [comment]
> ```
> 20:27:53.199 | error Building static HTML failed for path "/news/community-update-december-2020/"
> -- | --
> 20:27:53.208 | 6 \| import { Translate } from '../../i18n/utils/translate';
> 20:27:53.208 | 7 \|
> 20:27:53.208 | >  8 \| const Header = ({ pageContext: { locale: language } }) => {
> 20:27:53.208 | \|                                          ^
> 20:27:53.208 | 9 \|
> 20:27:53.208 | 10 \|   const [isOpen, setIsOpen] = useState(false);
> 20:27:53.208 | 11 \|   const translate = Translate();
> 20:27:53.208 |  
> 20:27:53.208 | WebpackError: TypeError: Cannot read property 'locale' of undefined
> 20:27:53.208 |  
> 20:27:53.208 | - index.jsx:8
> 20:27:53.209 | src/components/header/index.jsx:8:42
> ```
> 
> Looks like content pages are trying to use locale stuffs?

Indeed, I forgot to check individual pages because I've focused on other stuff more :+1: I will fix it in 1 day.

**Comment by ressonix** [comment]
Okay, I think we're good to go ahead and merge this into the `master` branch and go from there. Thanks for your awesome work so far @utkusaridede! It's super appreciated!

**Pull request merged**
